require("core.plugins")
require("core.keymaps")

require('core.plugin_config.bufferline')
require('core.plugin_config.gitsigns')
require('core.plugin_config.gruvbox')
require('core.plugin_config.lualine')
require('core.plugin_config.mason')
require('core.plugin_config.neoscroll')
require('core.plugin_config.nerdcommenter')
require('core.plugin_config.nvim-cmp')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.toggleterm')
require('core.plugin_config.vimtex')
require('core.plugin_config.wilder')
